/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using YL.Web.Api.ThirdParty.Onboarding.Client.Client;
using YL.Web.Api.ThirdParty.Onboarding.Client.Model;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDocumentSigningApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Gets the document signing for specified document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="YL.Web.Api.ThirdParty.Onboarding.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="documentSigningId">GUID used to identify the document signing</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>DocumentSigningViewModel</returns>
        DocumentSigningViewModel DocumentSigningDocumentSigningIdGet (Guid documentSigningId, string apiVersion = default(string));

        /// <summary>
        /// Gets the document signing for specified document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="YL.Web.Api.ThirdParty.Onboarding.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="documentSigningId">GUID used to identify the document signing</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>ApiResponse of DocumentSigningViewModel</returns>
        ApiResponse<DocumentSigningViewModel> DocumentSigningDocumentSigningIdGetWithHttpInfo (Guid documentSigningId, string apiVersion = default(string));
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDocumentSigningApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Gets the document signing for specified document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="YL.Web.Api.ThirdParty.Onboarding.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="documentSigningId">GUID used to identify the document signing</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>Task of DocumentSigningViewModel</returns>
        System.Threading.Tasks.Task<DocumentSigningViewModel> DocumentSigningDocumentSigningIdGetAsync (Guid documentSigningId, string apiVersion = default(string));

        /// <summary>
        /// Gets the document signing for specified document
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="YL.Web.Api.ThirdParty.Onboarding.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="documentSigningId">GUID used to identify the document signing</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>Task of ApiResponse (DocumentSigningViewModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<DocumentSigningViewModel>> DocumentSigningDocumentSigningIdGetAsyncWithHttpInfo (Guid documentSigningId, string apiVersion = default(string));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDocumentSigningApi : IDocumentSigningApiSync, IDocumentSigningApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DocumentSigningApi : IDocumentSigningApi
    {
        private YL.Web.Api.ThirdParty.Onboarding.Client.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentSigningApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DocumentSigningApi() : this((string) null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentSigningApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DocumentSigningApi(String basePath)
        {
            this.Configuration = YL.Web.Api.ThirdParty.Onboarding.Client.Client.Configuration.MergeConfigurations(
                YL.Web.Api.ThirdParty.Onboarding.Client.Client.GlobalConfiguration.Instance,
                new YL.Web.Api.ThirdParty.Onboarding.Client.Client.Configuration { BasePath = basePath }
            );
            this.Client = new YL.Web.Api.ThirdParty.Onboarding.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new YL.Web.Api.ThirdParty.Onboarding.Client.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = YL.Web.Api.ThirdParty.Onboarding.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentSigningApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DocumentSigningApi(YL.Web.Api.ThirdParty.Onboarding.Client.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = YL.Web.Api.ThirdParty.Onboarding.Client.Client.Configuration.MergeConfigurations(
                YL.Web.Api.ThirdParty.Onboarding.Client.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new YL.Web.Api.ThirdParty.Onboarding.Client.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new YL.Web.Api.ThirdParty.Onboarding.Client.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = YL.Web.Api.ThirdParty.Onboarding.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentSigningApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public DocumentSigningApi(YL.Web.Api.ThirdParty.Onboarding.Client.Client.ISynchronousClient client,YL.Web.Api.ThirdParty.Onboarding.Client.Client.IAsynchronousClient asyncClient, YL.Web.Api.ThirdParty.Onboarding.Client.Client.IReadableConfiguration configuration)
        {
            if(client == null) throw new ArgumentNullException("client");
            if(asyncClient == null) throw new ArgumentNullException("asyncClient");
            if(configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = YL.Web.Api.ThirdParty.Onboarding.Client.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public YL.Web.Api.ThirdParty.Onboarding.Client.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public YL.Web.Api.ThirdParty.Onboarding.Client.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public String GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public YL.Web.Api.ThirdParty.Onboarding.Client.Client.IReadableConfiguration Configuration {get; set;}

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public YL.Web.Api.ThirdParty.Onboarding.Client.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Gets the document signing for specified document 
        /// </summary>
        /// <exception cref="YL.Web.Api.ThirdParty.Onboarding.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="documentSigningId">GUID used to identify the document signing</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>DocumentSigningViewModel</returns>
        public DocumentSigningViewModel DocumentSigningDocumentSigningIdGet (Guid documentSigningId, string apiVersion = default(string))
        {
             YL.Web.Api.ThirdParty.Onboarding.Client.Client.ApiResponse<DocumentSigningViewModel> localVarResponse = DocumentSigningDocumentSigningIdGetWithHttpInfo(documentSigningId, apiVersion);
             return localVarResponse.Data;
        }

        /// <summary>
        /// Gets the document signing for specified document 
        /// </summary>
        /// <exception cref="YL.Web.Api.ThirdParty.Onboarding.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="documentSigningId">GUID used to identify the document signing</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>ApiResponse of DocumentSigningViewModel</returns>
        public YL.Web.Api.ThirdParty.Onboarding.Client.Client.ApiResponse< DocumentSigningViewModel > DocumentSigningDocumentSigningIdGetWithHttpInfo (Guid documentSigningId, string apiVersion = default(string))
        {
            // verify the required parameter 'documentSigningId' is set
            if (documentSigningId == null)
                throw new YL.Web.Api.ThirdParty.Onboarding.Client.Client.ApiException(400, "Missing required parameter 'documentSigningId' when calling DocumentSigningApi->DocumentSigningDocumentSigningIdGet");

            YL.Web.Api.ThirdParty.Onboarding.Client.Client.RequestOptions localVarRequestOptions = new YL.Web.Api.ThirdParty.Onboarding.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json",
                "application/xml"
            };

            var localVarContentType = YL.Web.Api.ThirdParty.Onboarding.Client.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = YL.Web.Api.ThirdParty.Onboarding.Client.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            if (documentSigningId != null)
                localVarRequestOptions.PathParameters.Add("documentSigningId", YL.Web.Api.ThirdParty.Onboarding.Client.Client.ClientUtils.ParameterToString(documentSigningId)); // path parameter
            if (apiVersion != null)
                localVarRequestOptions.HeaderParameters.Add("api-version", YL.Web.Api.ThirdParty.Onboarding.Client.Client.ClientUtils.ParameterToString(apiVersion)); // header parameter

            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get< DocumentSigningViewModel >("/DocumentSigning/{documentSigningId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DocumentSigningDocumentSigningIdGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// Gets the document signing for specified document 
        /// </summary>
        /// <exception cref="YL.Web.Api.ThirdParty.Onboarding.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="documentSigningId">GUID used to identify the document signing</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>Task of DocumentSigningViewModel</returns>
        public async System.Threading.Tasks.Task<DocumentSigningViewModel> DocumentSigningDocumentSigningIdGetAsync (Guid documentSigningId, string apiVersion = default(string))
        {
             YL.Web.Api.ThirdParty.Onboarding.Client.Client.ApiResponse<DocumentSigningViewModel> localVarResponse = await DocumentSigningDocumentSigningIdGetAsyncWithHttpInfo(documentSigningId, apiVersion);
             return localVarResponse.Data;

        }

        /// <summary>
        /// Gets the document signing for specified document 
        /// </summary>
        /// <exception cref="YL.Web.Api.ThirdParty.Onboarding.Client.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="documentSigningId">GUID used to identify the document signing</param>
        /// <param name="apiVersion"> (optional)</param>
        /// <returns>Task of ApiResponse (DocumentSigningViewModel)</returns>
        public async System.Threading.Tasks.Task<YL.Web.Api.ThirdParty.Onboarding.Client.Client.ApiResponse<DocumentSigningViewModel>> DocumentSigningDocumentSigningIdGetAsyncWithHttpInfo (Guid documentSigningId, string apiVersion = default(string))
        {
            // verify the required parameter 'documentSigningId' is set
            if (documentSigningId == null)
                throw new YL.Web.Api.ThirdParty.Onboarding.Client.Client.ApiException(400, "Missing required parameter 'documentSigningId' when calling DocumentSigningApi->DocumentSigningDocumentSigningIdGet");


            YL.Web.Api.ThirdParty.Onboarding.Client.Client.RequestOptions localVarRequestOptions = new YL.Web.Api.ThirdParty.Onboarding.Client.Client.RequestOptions();

            String[] _contentTypes = new String[] {
            };

            // to determine the Accept header
            String[] _accepts = new String[] {
                "application/json",
                "application/xml"
            };
            
            foreach (var _contentType in _contentTypes)
                localVarRequestOptions.HeaderParameters.Add("Content-Type", _contentType);
            
            foreach (var _accept in _accepts)
                localVarRequestOptions.HeaderParameters.Add("Accept", _accept);
            
            if (documentSigningId != null)
                localVarRequestOptions.PathParameters.Add("documentSigningId", YL.Web.Api.ThirdParty.Onboarding.Client.Client.ClientUtils.ParameterToString(documentSigningId)); // path parameter
            if (apiVersion != null)
                localVarRequestOptions.HeaderParameters.Add("api-version", YL.Web.Api.ThirdParty.Onboarding.Client.Client.ClientUtils.ParameterToString(apiVersion)); // header parameter

            // authentication (oauth2) required
            // oauth required
            if (!String.IsNullOrEmpty(this.Configuration.AccessToken))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.GetAsync<DocumentSigningViewModel>("/DocumentSigning/{documentSigningId}", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DocumentSigningDocumentSigningIdGet", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
