/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Onboarding.Client.Api;
using YL.Web.Api.ThirdParty.Onboarding.Client.Model;
using YL.Web.Api.ThirdParty.Onboarding.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Test
{
    /// <summary>
    ///  Class for testing AccountV2StepModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccountV2StepModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccountV2StepModel
        //private AccountV2StepModel instance;

        public AccountV2StepModelTests()
        {
            // TODO uncomment below to create an instance of AccountV2StepModel
            //instance = new AccountV2StepModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccountV2StepModel
        /// </summary>
        [Fact]
        public void AccountV2StepModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AccountV2StepModel
            //Assert.IsInstanceOfType<AccountV2StepModel> (instance, "variable 'instance' is a AccountV2StepModel");
        }


        /// <summary>
        /// Test the property 'LeadId'
        /// </summary>
        [Fact]
        public void LeadIdTest()
        {
            // TODO unit test for the property 'LeadId'
        }
        /// <summary>
        /// Test the property 'SortCode'
        /// </summary>
        [Fact]
        public void SortCodeTest()
        {
            // TODO unit test for the property 'SortCode'
        }
        /// <summary>
        /// Test the property 'AccountNumber'
        /// </summary>
        [Fact]
        public void AccountNumberTest()
        {
            // TODO unit test for the property 'AccountNumber'
        }
        /// <summary>
        /// Test the property 'Swift'
        /// </summary>
        [Fact]
        public void SwiftTest()
        {
            // TODO unit test for the property 'Swift'
        }
        /// <summary>
        /// Test the property 'Iban'
        /// </summary>
        [Fact]
        public void IbanTest()
        {
            // TODO unit test for the property 'Iban'
        }
        /// <summary>
        /// Test the property 'BankName'
        /// </summary>
        [Fact]
        public void BankNameTest()
        {
            // TODO unit test for the property 'BankName'
        }
        /// <summary>
        /// Test the property 'ConfirmedCompanyAccount'
        /// </summary>
        [Fact]
        public void ConfirmedCompanyAccountTest()
        {
            // TODO unit test for the property 'ConfirmedCompanyAccount'
        }

    }

}
