/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Onboarding.Client.Api;
using YL.Web.Api.ThirdParty.Onboarding.Client.Model;
using YL.Web.Api.ThirdParty.Onboarding.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Test
{
    /// <summary>
    ///  Class for testing AdvanceSignUpData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AdvanceSignUpDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AdvanceSignUpData
        //private AdvanceSignUpData instance;

        public AdvanceSignUpDataTests()
        {
            // TODO uncomment below to create an instance of AdvanceSignUpData
            //instance = new AdvanceSignUpData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AdvanceSignUpData
        /// </summary>
        [Fact]
        public void AdvanceSignUpDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AdvanceSignUpData
            //Assert.IsInstanceOfType<AdvanceSignUpData> (instance, "variable 'instance' is a AdvanceSignUpData");
        }


        /// <summary>
        /// Test the property 'CurrencyISOCode'
        /// </summary>
        [Fact]
        public void CurrencyISOCodeTest()
        {
            // TODO unit test for the property 'CurrencyISOCode'
        }
        /// <summary>
        /// Test the property 'MonthlyRevenue'
        /// </summary>
        [Fact]
        public void MonthlyRevenueTest()
        {
            // TODO unit test for the property 'MonthlyRevenue'
        }
        /// <summary>
        /// Test the property 'MonthlyRevenueSliderIndex'
        /// </summary>
        [Fact]
        public void MonthlyRevenueSliderIndexTest()
        {
            // TODO unit test for the property 'MonthlyRevenueSliderIndex'
        }
        /// <summary>
        /// Test the property 'NumberOfPaymentsPerMonth'
        /// </summary>
        [Fact]
        public void NumberOfPaymentsPerMonthTest()
        {
            // TODO unit test for the property 'NumberOfPaymentsPerMonth'
        }
        /// <summary>
        /// Test the property 'NumberOfPaymentsPerMonthSliderIndex'
        /// </summary>
        [Fact]
        public void NumberOfPaymentsPerMonthSliderIndexTest()
        {
            // TODO unit test for the property 'NumberOfPaymentsPerMonthSliderIndex'
        }
        /// <summary>
        /// Test the property 'SweepPercentage'
        /// </summary>
        [Fact]
        public void SweepPercentageTest()
        {
            // TODO unit test for the property 'SweepPercentage'
        }
        /// <summary>
        /// Test the property 'TimeOperating'
        /// </summary>
        [Fact]
        public void TimeOperatingTest()
        {
            // TODO unit test for the property 'TimeOperating'
        }
        /// <summary>
        /// Test the property 'TimeOperatingSliderIndex'
        /// </summary>
        [Fact]
        public void TimeOperatingSliderIndexTest()
        {
            // TODO unit test for the property 'TimeOperatingSliderIndex'
        }
        /// <summary>
        /// Test the property 'SizeOfAdvance'
        /// </summary>
        [Fact]
        public void SizeOfAdvanceTest()
        {
            // TODO unit test for the property 'SizeOfAdvance'
        }
        /// <summary>
        /// Test the property 'SizeOfAdvanceSliderIndex'
        /// </summary>
        [Fact]
        public void SizeOfAdvanceSliderIndexTest()
        {
            // TODO unit test for the property 'SizeOfAdvanceSliderIndex'
        }
        /// <summary>
        /// Test the property 'HowMuchToPayBack'
        /// </summary>
        [Fact]
        public void HowMuchToPayBackTest()
        {
            // TODO unit test for the property 'HowMuchToPayBack'
        }
        /// <summary>
        /// Test the property 'PayBackInMonths'
        /// </summary>
        [Fact]
        public void PayBackInMonthsTest()
        {
            // TODO unit test for the property 'PayBackInMonths'
        }

    }

}
