/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Onboarding.Client.Api;
using YL.Web.Api.ThirdParty.Onboarding.Client.Model;
using YL.Web.Api.ThirdParty.Onboarding.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Test
{
    /// <summary>
    ///  Class for testing CreateThirdPartyAdvanceOnboardingResultModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateThirdPartyAdvanceOnboardingResultModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateThirdPartyAdvanceOnboardingResultModel
        //private CreateThirdPartyAdvanceOnboardingResultModel instance;

        public CreateThirdPartyAdvanceOnboardingResultModelTests()
        {
            // TODO uncomment below to create an instance of CreateThirdPartyAdvanceOnboardingResultModel
            //instance = new CreateThirdPartyAdvanceOnboardingResultModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateThirdPartyAdvanceOnboardingResultModel
        /// </summary>
        [Fact]
        public void CreateThirdPartyAdvanceOnboardingResultModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreateThirdPartyAdvanceOnboardingResultModel
            //Assert.IsInstanceOfType<CreateThirdPartyAdvanceOnboardingResultModel> (instance, "variable 'instance' is a CreateThirdPartyAdvanceOnboardingResultModel");
        }


        /// <summary>
        /// Test the property 'LeadId'
        /// </summary>
        [Fact]
        public void LeadIdTest()
        {
            // TODO unit test for the property 'LeadId'
        }
        /// <summary>
        /// Test the property 'LeadURL'
        /// </summary>
        [Fact]
        public void LeadURLTest()
        {
            // TODO unit test for the property 'LeadURL'
        }
        /// <summary>
        /// Test the property 'SignUpURL'
        /// </summary>
        [Fact]
        public void SignUpURLTest()
        {
            // TODO unit test for the property 'SignUpURL'
        }

    }

}
