/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Onboarding.Client.Api;
using YL.Web.Api.ThirdParty.Onboarding.Client.Model;
using YL.Web.Api.ThirdParty.Onboarding.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Test
{
    /// <summary>
    ///  Class for testing CreditRatingBandParameters
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreditRatingBandParametersTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreditRatingBandParameters
        //private CreditRatingBandParameters instance;

        public CreditRatingBandParametersTests()
        {
            // TODO uncomment below to create an instance of CreditRatingBandParameters
            //instance = new CreditRatingBandParameters();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreditRatingBandParameters
        /// </summary>
        [Fact]
        public void CreditRatingBandParametersInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" CreditRatingBandParameters
            //Assert.IsInstanceOfType<CreditRatingBandParameters> (instance, "variable 'instance' is a CreditRatingBandParameters");
        }


        /// <summary>
        /// Test the property 'Rating'
        /// </summary>
        [Fact]
        public void RatingTest()
        {
            // TODO unit test for the property 'Rating'
        }
        /// <summary>
        /// Test the property 'LowerLimit'
        /// </summary>
        [Fact]
        public void LowerLimitTest()
        {
            // TODO unit test for the property 'LowerLimit'
        }
        /// <summary>
        /// Test the property 'UpperLimit'
        /// </summary>
        [Fact]
        public void UpperLimitTest()
        {
            // TODO unit test for the property 'UpperLimit'
        }
        /// <summary>
        /// Test the property 'TargetTerm'
        /// </summary>
        [Fact]
        public void TargetTermTest()
        {
            // TODO unit test for the property 'TargetTerm'
        }
        /// <summary>
        /// Test the property 'Fee'
        /// </summary>
        [Fact]
        public void FeeTest()
        {
            // TODO unit test for the property 'Fee'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'CountryCode'
        /// </summary>
        [Fact]
        public void CountryCodeTest()
        {
            // TODO unit test for the property 'CountryCode'
        }
        /// <summary>
        /// Test the property 'LoanSweep2'
        /// </summary>
        [Fact]
        public void LoanSweep2Test()
        {
            // TODO unit test for the property 'LoanSweep2'
        }
        /// <summary>
        /// Test the property 'LoanSweep3'
        /// </summary>
        [Fact]
        public void LoanSweep3Test()
        {
            // TODO unit test for the property 'LoanSweep3'
        }

    }

}
