/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Onboarding.Client.Api;
using YL.Web.Api.ThirdParty.Onboarding.Client.Model;
using YL.Web.Api.ThirdParty.Onboarding.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Test
{
    /// <summary>
    ///  Class for testing DocumentSigningViewModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentSigningViewModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DocumentSigningViewModel
        //private DocumentSigningViewModel instance;

        public DocumentSigningViewModelTests()
        {
            // TODO uncomment below to create an instance of DocumentSigningViewModel
            //instance = new DocumentSigningViewModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocumentSigningViewModel
        /// </summary>
        [Fact]
        public void DocumentSigningViewModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" DocumentSigningViewModel
            //Assert.IsInstanceOfType<DocumentSigningViewModel> (instance, "variable 'instance' is a DocumentSigningViewModel");
        }


        /// <summary>
        /// Test the property 'DocumentSigningId'
        /// </summary>
        [Fact]
        public void DocumentSigningIdTest()
        {
            // TODO unit test for the property 'DocumentSigningId'
        }
        /// <summary>
        /// Test the property 'Documents'
        /// </summary>
        [Fact]
        public void DocumentsTest()
        {
            // TODO unit test for the property 'Documents'
        }
        /// <summary>
        /// Test the property 'SignatorySigningViews'
        /// </summary>
        [Fact]
        public void SignatorySigningViewsTest()
        {
            // TODO unit test for the property 'SignatorySigningViews'
        }
        /// <summary>
        /// Test the property 'SignedDocuments'
        /// </summary>
        [Fact]
        public void SignedDocumentsTest()
        {
            // TODO unit test for the property 'SignedDocuments'
        }

    }

}
