/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Onboarding.Client.Api;
using YL.Web.Api.ThirdParty.Onboarding.Client.Model;
using YL.Web.Api.ThirdParty.Onboarding.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Test
{
    /// <summary>
    ///  Class for testing Document
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Document
        //private Document instance;

        public DocumentTests()
        {
            // TODO uncomment below to create an instance of Document
            //instance = new Document();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Document
        /// </summary>
        [Fact]
        public void DocumentInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Document
            //Assert.IsInstanceOfType<Document> (instance, "variable 'instance' is a Document");
        }


        /// <summary>
        /// Test the property 'DocumentId'
        /// </summary>
        [Fact]
        public void DocumentIdTest()
        {
            // TODO unit test for the property 'DocumentId'
        }
        /// <summary>
        /// Test the property 'DocumentName'
        /// </summary>
        [Fact]
        public void DocumentNameTest()
        {
            // TODO unit test for the property 'DocumentName'
        }
        /// <summary>
        /// Test the property 'DocumentType'
        /// </summary>
        [Fact]
        public void DocumentTypeTest()
        {
            // TODO unit test for the property 'DocumentType'
        }
        /// <summary>
        /// Test the property 'DateTimeUploaded'
        /// </summary>
        [Fact]
        public void DateTimeUploadedTest()
        {
            // TODO unit test for the property 'DateTimeUploaded'
        }

    }

}
