/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Onboarding.Client.Api;
using YL.Web.Api.ThirdParty.Onboarding.Client.Model;
using YL.Web.Api.ThirdParty.Onboarding.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Test
{
    /// <summary>
    ///  Class for testing KycDocumentsV2StepModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KycDocumentsV2StepModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for KycDocumentsV2StepModel
        //private KycDocumentsV2StepModel instance;

        public KycDocumentsV2StepModelTests()
        {
            // TODO uncomment below to create an instance of KycDocumentsV2StepModel
            //instance = new KycDocumentsV2StepModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KycDocumentsV2StepModel
        /// </summary>
        [Fact]
        public void KycDocumentsV2StepModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" KycDocumentsV2StepModel
            //Assert.IsInstanceOfType<KycDocumentsV2StepModel> (instance, "variable 'instance' is a KycDocumentsV2StepModel");
        }


        /// <summary>
        /// Test the property 'CompanyDocuments'
        /// </summary>
        [Fact]
        public void CompanyDocumentsTest()
        {
            // TODO unit test for the property 'CompanyDocuments'
        }
        /// <summary>
        /// Test the property 'SignificantPersonDocuments'
        /// </summary>
        [Fact]
        public void SignificantPersonDocumentsTest()
        {
            // TODO unit test for the property 'SignificantPersonDocuments'
        }
        /// <summary>
        /// Test the property 'BankStatements'
        /// </summary>
        [Fact]
        public void BankStatementsTest()
        {
            // TODO unit test for the property 'BankStatements'
        }
        /// <summary>
        /// Test the property 'LeadId'
        /// </summary>
        [Fact]
        public void LeadIdTest()
        {
            // TODO unit test for the property 'LeadId'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }
        /// <summary>
        /// Test the property 'CompanyType'
        /// </summary>
        [Fact]
        public void CompanyTypeTest()
        {
            // TODO unit test for the property 'CompanyType'
        }

    }

}
