/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Onboarding.Client.Api;
using YL.Web.Api.ThirdParty.Onboarding.Client.Model;
using YL.Web.Api.ThirdParty.Onboarding.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Test
{
    /// <summary>
    ///  Class for testing KycQuestions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class KycQuestionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for KycQuestions
        //private KycQuestions instance;

        public KycQuestionsTests()
        {
            // TODO uncomment below to create an instance of KycQuestions
            //instance = new KycQuestions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of KycQuestions
        /// </summary>
        [Fact]
        public void KycQuestionsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" KycQuestions
            //Assert.IsInstanceOfType<KycQuestions> (instance, "variable 'instance' is a KycQuestions");
        }


        /// <summary>
        /// Test the property 'EverTerminated'
        /// </summary>
        [Fact]
        public void EverTerminatedTest()
        {
            // TODO unit test for the property 'EverTerminated'
        }
        /// <summary>
        /// Test the property 'AnyPoliticallyExposedPeople'
        /// </summary>
        [Fact]
        public void AnyPoliticallyExposedPeopleTest()
        {
            // TODO unit test for the property 'AnyPoliticallyExposedPeople'
        }
        /// <summary>
        /// Test the property 'BusinessArea'
        /// </summary>
        [Fact]
        public void BusinessAreaTest()
        {
            // TODO unit test for the property 'BusinessArea'
        }
        /// <summary>
        /// Test the property 'CountriesOperateIn'
        /// </summary>
        [Fact]
        public void CountriesOperateInTest()
        {
            // TODO unit test for the property 'CountriesOperateIn'
        }
        /// <summary>
        /// Test the property 'AnyLawEnforcedSanctions'
        /// </summary>
        [Fact]
        public void AnyLawEnforcedSanctionsTest()
        {
            // TODO unit test for the property 'AnyLawEnforcedSanctions'
        }
        /// <summary>
        /// Test the property 'AnyTerrorismFinancing'
        /// </summary>
        [Fact]
        public void AnyTerrorismFinancingTest()
        {
            // TODO unit test for the property 'AnyTerrorismFinancing'
        }
        /// <summary>
        /// Test the property 'AnyCriminals'
        /// </summary>
        [Fact]
        public void AnyCriminalsTest()
        {
            // TODO unit test for the property 'AnyCriminals'
        }

    }

}
