/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Onboarding.Client.Api;
using YL.Web.Api.ThirdParty.Onboarding.Client.Model;
using YL.Web.Api.ThirdParty.Onboarding.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Test
{
    /// <summary>
    ///  Class for testing LoanSizingModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LoanSizingModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LoanSizingModel
        //private LoanSizingModel instance;

        public LoanSizingModelTests()
        {
            // TODO uncomment below to create an instance of LoanSizingModel
            //instance = new LoanSizingModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LoanSizingModel
        /// </summary>
        [Fact]
        public void LoanSizingModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanSizingModel
            //Assert.IsInstanceOfType<LoanSizingModel> (instance, "variable 'instance' is a LoanSizingModel");
        }


        /// <summary>
        /// Test the property 'LoanSizingProcessId'
        /// </summary>
        [Fact]
        public void LoanSizingProcessIdTest()
        {
            // TODO unit test for the property 'LoanSizingProcessId'
        }
        /// <summary>
        /// Test the property 'CompanyNumber'
        /// </summary>
        [Fact]
        public void CompanyNumberTest()
        {
            // TODO unit test for the property 'CompanyNumber'
        }
        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Fact]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'AverageMonthlyRevenue'
        /// </summary>
        [Fact]
        public void AverageMonthlyRevenueTest()
        {
            // TODO unit test for the property 'AverageMonthlyRevenue'
        }
        /// <summary>
        /// Test the property 'CreditRatingBandParameters'
        /// </summary>
        [Fact]
        public void CreditRatingBandParametersTest()
        {
            // TODO unit test for the property 'CreditRatingBandParameters'
        }
        /// <summary>
        /// Test the property 'LoanOption1'
        /// </summary>
        [Fact]
        public void LoanOption1Test()
        {
            // TODO unit test for the property 'LoanOption1'
        }
        /// <summary>
        /// Test the property 'LoanOption2'
        /// </summary>
        [Fact]
        public void LoanOption2Test()
        {
            // TODO unit test for the property 'LoanOption2'
        }
        /// <summary>
        /// Test the property 'LoanOption3'
        /// </summary>
        [Fact]
        public void LoanOption3Test()
        {
            // TODO unit test for the property 'LoanOption3'
        }

    }

}
