/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Onboarding.Client.Api;
using YL.Web.Api.ThirdParty.Onboarding.Client.Model;
using YL.Web.Api.ThirdParty.Onboarding.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Test
{
    /// <summary>
    ///  Class for testing LoanOptionModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LoanOptionModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LoanOptionModel
        //private LoanOptionModel instance;

        public LoanOptionModelTests()
        {
            // TODO uncomment below to create an instance of LoanOptionModel
            //instance = new LoanOptionModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LoanOptionModel
        /// </summary>
        [Fact]
        public void LoanOptionModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" LoanOptionModel
            //Assert.IsInstanceOfType<LoanOptionModel> (instance, "variable 'instance' is a LoanOptionModel");
        }


        /// <summary>
        /// Test the property 'FundedAmount'
        /// </summary>
        [Fact]
        public void FundedAmountTest()
        {
            // TODO unit test for the property 'FundedAmount'
        }
        /// <summary>
        /// Test the property 'Fee'
        /// </summary>
        [Fact]
        public void FeeTest()
        {
            // TODO unit test for the property 'Fee'
        }
        /// <summary>
        /// Test the property 'LoanAmount'
        /// </summary>
        [Fact]
        public void LoanAmountTest()
        {
            // TODO unit test for the property 'LoanAmount'
        }
        /// <summary>
        /// Test the property 'Sweep'
        /// </summary>
        [Fact]
        public void SweepTest()
        {
            // TODO unit test for the property 'Sweep'
        }
        /// <summary>
        /// Test the property 'CalculatedFundedAmount'
        /// </summary>
        [Fact]
        public void CalculatedFundedAmountTest()
        {
            // TODO unit test for the property 'CalculatedFundedAmount'
        }
        /// <summary>
        /// Test the property 'CalculatedFee'
        /// </summary>
        [Fact]
        public void CalculatedFeeTest()
        {
            // TODO unit test for the property 'CalculatedFee'
        }
        /// <summary>
        /// Test the property 'CalculatedLoanAmount'
        /// </summary>
        [Fact]
        public void CalculatedLoanAmountTest()
        {
            // TODO unit test for the property 'CalculatedLoanAmount'
        }
        /// <summary>
        /// Test the property 'CalculatedSweep'
        /// </summary>
        [Fact]
        public void CalculatedSweepTest()
        {
            // TODO unit test for the property 'CalculatedSweep'
        }
        /// <summary>
        /// Test the property 'CurrencyCode'
        /// </summary>
        [Fact]
        public void CurrencyCodeTest()
        {
            // TODO unit test for the property 'CurrencyCode'
        }

    }

}
