/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Onboarding.Client.Api;
using YL.Web.Api.ThirdParty.Onboarding.Client.Model;
using YL.Web.Api.ThirdParty.Onboarding.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Test
{
    /// <summary>
    ///  Class for testing MerchantIdsModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MerchantIdsModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MerchantIdsModel
        //private MerchantIdsModel instance;

        public MerchantIdsModelTests()
        {
            // TODO uncomment below to create an instance of MerchantIdsModel
            //instance = new MerchantIdsModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MerchantIdsModel
        /// </summary>
        [Fact]
        public void MerchantIdsModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MerchantIdsModel
            //Assert.IsInstanceOfType<MerchantIdsModel> (instance, "variable 'instance' is a MerchantIdsModel");
        }


        /// <summary>
        /// Test the property 'MasterMidId'
        /// </summary>
        [Fact]
        public void MasterMidIdTest()
        {
            // TODO unit test for the property 'MasterMidId'
        }
        /// <summary>
        /// Test the property 'OutletMidIds'
        /// </summary>
        [Fact]
        public void OutletMidIdsTest()
        {
            // TODO unit test for the property 'OutletMidIds'
        }
        /// <summary>
        /// Test the property 'AllMerchantIds'
        /// </summary>
        [Fact]
        public void AllMerchantIdsTest()
        {
            // TODO unit test for the property 'AllMerchantIds'
        }

    }

}
