/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Onboarding.Client.Api;
using YL.Web.Api.ThirdParty.Onboarding.Client.Model;
using YL.Web.Api.ThirdParty.Onboarding.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Test
{
    /// <summary>
    ///  Class for testing OfferStepModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OfferStepModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OfferStepModel
        //private OfferStepModel instance;

        public OfferStepModelTests()
        {
            // TODO uncomment below to create an instance of OfferStepModel
            //instance = new OfferStepModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OfferStepModel
        /// </summary>
        [Fact]
        public void OfferStepModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OfferStepModel
            //Assert.IsInstanceOfType<OfferStepModel> (instance, "variable 'instance' is a OfferStepModel");
        }


        /// <summary>
        /// Test the property 'LeadId'
        /// </summary>
        [Fact]
        public void LeadIdTest()
        {
            // TODO unit test for the property 'LeadId'
        }
        /// <summary>
        /// Test the property 'YouWillGet'
        /// </summary>
        [Fact]
        public void YouWillGetTest()
        {
            // TODO unit test for the property 'YouWillGet'
        }
        /// <summary>
        /// Test the property 'YouWillRepay'
        /// </summary>
        [Fact]
        public void YouWillRepayTest()
        {
            // TODO unit test for the property 'YouWillRepay'
        }
        /// <summary>
        /// Test the property 'CurrencyISOCode'
        /// </summary>
        [Fact]
        public void CurrencyISOCodeTest()
        {
            // TODO unit test for the property 'CurrencyISOCode'
        }
        /// <summary>
        /// Test the property 'Sweep'
        /// </summary>
        [Fact]
        public void SweepTest()
        {
            // TODO unit test for the property 'Sweep'
        }
        /// <summary>
        /// Test the property 'UnsignedLoanDocument'
        /// </summary>
        [Fact]
        public void UnsignedLoanDocumentTest()
        {
            // TODO unit test for the property 'UnsignedLoanDocument'
        }
        /// <summary>
        /// Test the property 'UnsignedLoanDocumentDownloaded'
        /// </summary>
        [Fact]
        public void UnsignedLoanDocumentDownloadedTest()
        {
            // TODO unit test for the property 'UnsignedLoanDocumentDownloaded'
        }
        /// <summary>
        /// Test the property 'UnsignedAccountDocument'
        /// </summary>
        [Fact]
        public void UnsignedAccountDocumentTest()
        {
            // TODO unit test for the property 'UnsignedAccountDocument'
        }
        /// <summary>
        /// Test the property 'UnsignedAccountDocumentDownloaded'
        /// </summary>
        [Fact]
        public void UnsignedAccountDocumentDownloadedTest()
        {
            // TODO unit test for the property 'UnsignedAccountDocumentDownloaded'
        }
        /// <summary>
        /// Test the property 'DocumentSigningId'
        /// </summary>
        [Fact]
        public void DocumentSigningIdTest()
        {
            // TODO unit test for the property 'DocumentSigningId'
        }
        /// <summary>
        /// Test the property 'SortCode'
        /// </summary>
        [Fact]
        public void SortCodeTest()
        {
            // TODO unit test for the property 'SortCode'
        }
        /// <summary>
        /// Test the property 'AccountNumber'
        /// </summary>
        [Fact]
        public void AccountNumberTest()
        {
            // TODO unit test for the property 'AccountNumber'
        }
        /// <summary>
        /// Test the property 'Swift'
        /// </summary>
        [Fact]
        public void SwiftTest()
        {
            // TODO unit test for the property 'Swift'
        }
        /// <summary>
        /// Test the property 'Iban'
        /// </summary>
        [Fact]
        public void IbanTest()
        {
            // TODO unit test for the property 'Iban'
        }
        /// <summary>
        /// Test the property 'BankName'
        /// </summary>
        [Fact]
        public void BankNameTest()
        {
            // TODO unit test for the property 'BankName'
        }
        /// <summary>
        /// Test the property 'ConfirmedCompanyAccount'
        /// </summary>
        [Fact]
        public void ConfirmedCompanyAccountTest()
        {
            // TODO unit test for the property 'ConfirmedCompanyAccount'
        }

    }

}
