/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Onboarding.Client.Api;
using YL.Web.Api.ThirdParty.Onboarding.Client.Model;
using YL.Web.Api.ThirdParty.Onboarding.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Test
{
    /// <summary>
    ///  Class for testing OnboardingOrganisationDetailsModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OnboardingOrganisationDetailsModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OnboardingOrganisationDetailsModel
        //private OnboardingOrganisationDetailsModel instance;

        public OnboardingOrganisationDetailsModelTests()
        {
            // TODO uncomment below to create an instance of OnboardingOrganisationDetailsModel
            //instance = new OnboardingOrganisationDetailsModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OnboardingOrganisationDetailsModel
        /// </summary>
        [Fact]
        public void OnboardingOrganisationDetailsModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OnboardingOrganisationDetailsModel
            //Assert.IsInstanceOfType<OnboardingOrganisationDetailsModel> (instance, "variable 'instance' is a OnboardingOrganisationDetailsModel");
        }


        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Fact]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'CompanyNumber'
        /// </summary>
        [Fact]
        public void CompanyNumberTest()
        {
            // TODO unit test for the property 'CompanyNumber'
        }
        /// <summary>
        /// Test the property 'VatNumber'
        /// </summary>
        [Fact]
        public void VatNumberTest()
        {
            // TODO unit test for the property 'VatNumber'
        }
        /// <summary>
        /// Test the property 'FormationDate'
        /// </summary>
        [Fact]
        public void FormationDateTest()
        {
            // TODO unit test for the property 'FormationDate'
        }
        /// <summary>
        /// Test the property 'CompanyType'
        /// </summary>
        [Fact]
        public void CompanyTypeTest()
        {
            // TODO unit test for the property 'CompanyType'
        }
        /// <summary>
        /// Test the property 'RegisteredAddress'
        /// </summary>
        [Fact]
        public void RegisteredAddressTest()
        {
            // TODO unit test for the property 'RegisteredAddress'
        }
        /// <summary>
        /// Test the property 'CountryISOCode'
        /// </summary>
        [Fact]
        public void CountryISOCodeTest()
        {
            // TODO unit test for the property 'CountryISOCode'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Industries'
        /// </summary>
        [Fact]
        public void IndustriesTest()
        {
            // TODO unit test for the property 'Industries'
        }
        /// <summary>
        /// Test the property 'KeyContactName'
        /// </summary>
        [Fact]
        public void KeyContactNameTest()
        {
            // TODO unit test for the property 'KeyContactName'
        }
        /// <summary>
        /// Test the property 'CompanyWebsite'
        /// </summary>
        [Fact]
        public void CompanyWebsiteTest()
        {
            // TODO unit test for the property 'CompanyWebsite'
        }
        /// <summary>
        /// Test the property 'ContactPhoneNumber'
        /// </summary>
        [Fact]
        public void ContactPhoneNumberTest()
        {
            // TODO unit test for the property 'ContactPhoneNumber'
        }
        /// <summary>
        /// Test the property 'ContactEmailAddress'
        /// </summary>
        [Fact]
        public void ContactEmailAddressTest()
        {
            // TODO unit test for the property 'ContactEmailAddress'
        }
        /// <summary>
        /// Test the property 'MerchantIds'
        /// </summary>
        [Fact]
        public void MerchantIdsTest()
        {
            // TODO unit test for the property 'MerchantIds'
        }
        /// <summary>
        /// Test the property 'ConfirmedCreditSearch'
        /// </summary>
        [Fact]
        public void ConfirmedCreditSearchTest()
        {
            // TODO unit test for the property 'ConfirmedCreditSearch'
        }

    }

}
