/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Onboarding.Client.Api;
using YL.Web.Api.ThirdParty.Onboarding.Client.Model;
using YL.Web.Api.ThirdParty.Onboarding.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Test
{
    /// <summary>
    ///  Class for testing OnboardingOfferModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OnboardingOfferModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OnboardingOfferModel
        //private OnboardingOfferModel instance;

        public OnboardingOfferModelTests()
        {
            // TODO uncomment below to create an instance of OnboardingOfferModel
            //instance = new OnboardingOfferModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OnboardingOfferModel
        /// </summary>
        [Fact]
        public void OnboardingOfferModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OnboardingOfferModel
            //Assert.IsInstanceOfType<OnboardingOfferModel> (instance, "variable 'instance' is a OnboardingOfferModel");
        }


        /// <summary>
        /// Test the property 'YouWillGet'
        /// </summary>
        [Fact]
        public void YouWillGetTest()
        {
            // TODO unit test for the property 'YouWillGet'
        }
        /// <summary>
        /// Test the property 'YouWillRepay'
        /// </summary>
        [Fact]
        public void YouWillRepayTest()
        {
            // TODO unit test for the property 'YouWillRepay'
        }
        /// <summary>
        /// Test the property 'CurrencyISOCode'
        /// </summary>
        [Fact]
        public void CurrencyISOCodeTest()
        {
            // TODO unit test for the property 'CurrencyISOCode'
        }
        /// <summary>
        /// Test the property 'Sweep'
        /// </summary>
        [Fact]
        public void SweepTest()
        {
            // TODO unit test for the property 'Sweep'
        }

    }

}
