/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Onboarding.Client.Api;
using YL.Web.Api.ThirdParty.Onboarding.Client.Model;
using YL.Web.Api.ThirdParty.Onboarding.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Test
{
    /// <summary>
    ///  Class for testing OnboardingV2View
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OnboardingV2ViewTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OnboardingV2View
        //private OnboardingV2View instance;

        public OnboardingV2ViewTests()
        {
            // TODO uncomment below to create an instance of OnboardingV2View
            //instance = new OnboardingV2View();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OnboardingV2View
        /// </summary>
        [Fact]
        public void OnboardingV2ViewInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" OnboardingV2View
            //Assert.IsInstanceOfType<OnboardingV2View> (instance, "variable 'instance' is a OnboardingV2View");
        }


        /// <summary>
        /// Test the property 'LeadSourceLendingPartnerId'
        /// </summary>
        [Fact]
        public void LeadSourceLendingPartnerIdTest()
        {
            // TODO unit test for the property 'LeadSourceLendingPartnerId'
        }
        /// <summary>
        /// Test the property 'OnboardingState'
        /// </summary>
        [Fact]
        public void OnboardingStateTest()
        {
            // TODO unit test for the property 'OnboardingState'
        }
        /// <summary>
        /// Test the property 'OnboardingStateReason'
        /// </summary>
        [Fact]
        public void OnboardingStateReasonTest()
        {
            // TODO unit test for the property 'OnboardingStateReason'
        }
        /// <summary>
        /// Test the property 'OrganisationDetailsStepComplete'
        /// </summary>
        [Fact]
        public void OrganisationDetailsStepCompleteTest()
        {
            // TODO unit test for the property 'OrganisationDetailsStepComplete'
        }
        /// <summary>
        /// Test the property 'PaymentDataStepComplete'
        /// </summary>
        [Fact]
        public void PaymentDataStepCompleteTest()
        {
            // TODO unit test for the property 'PaymentDataStepComplete'
        }
        /// <summary>
        /// Test the property 'OfferStepComplete'
        /// </summary>
        [Fact]
        public void OfferStepCompleteTest()
        {
            // TODO unit test for the property 'OfferStepComplete'
        }
        /// <summary>
        /// Test the property 'KycQuestionsStepComplete'
        /// </summary>
        [Fact]
        public void KycQuestionsStepCompleteTest()
        {
            // TODO unit test for the property 'KycQuestionsStepComplete'
        }
        /// <summary>
        /// Test the property 'KycDocumentsStepComplete'
        /// </summary>
        [Fact]
        public void KycDocumentsStepCompleteTest()
        {
            // TODO unit test for the property 'KycDocumentsStepComplete'
        }
        /// <summary>
        /// Test the property 'AccountStepComplete'
        /// </summary>
        [Fact]
        public void AccountStepCompleteTest()
        {
            // TODO unit test for the property 'AccountStepComplete'
        }
        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Fact]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'LeadType'
        /// </summary>
        [Fact]
        public void LeadTypeTest()
        {
            // TODO unit test for the property 'LeadType'
        }

    }

}
