/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Onboarding.Client.Api;
using YL.Web.Api.ThirdParty.Onboarding.Client.Model;
using YL.Web.Api.ThirdParty.Onboarding.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Test
{
    /// <summary>
    ///  Class for testing PaymentDataStepView
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentDataStepViewTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentDataStepView
        //private PaymentDataStepView instance;

        public PaymentDataStepViewTests()
        {
            // TODO uncomment below to create an instance of PaymentDataStepView
            //instance = new PaymentDataStepView();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentDataStepView
        /// </summary>
        [Fact]
        public void PaymentDataStepViewInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PaymentDataStepView
            //Assert.IsInstanceOfType<PaymentDataStepView> (instance, "variable 'instance' is a PaymentDataStepView");
        }


        /// <summary>
        /// Test the property 'LeadId'
        /// </summary>
        [Fact]
        public void LeadIdTest()
        {
            // TODO unit test for the property 'LeadId'
        }
        /// <summary>
        /// Test the property 'PaymentDataDocuments'
        /// </summary>
        [Fact]
        public void PaymentDataDocumentsTest()
        {
            // TODO unit test for the property 'PaymentDataDocuments'
        }
        /// <summary>
        /// Test the property 'GatewaysUsed'
        /// </summary>
        [Fact]
        public void GatewaysUsedTest()
        {
            // TODO unit test for the property 'GatewaysUsed'
        }
        /// <summary>
        /// Test the property 'CalculatorData'
        /// </summary>
        [Fact]
        public void CalculatorDataTest()
        {
            // TODO unit test for the property 'CalculatorData'
        }
        /// <summary>
        /// Test the property 'Country'
        /// </summary>
        [Fact]
        public void CountryTest()
        {
            // TODO unit test for the property 'Country'
        }

    }

}
