/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Onboarding.Client.Api;
using YL.Web.Api.ThirdParty.Onboarding.Client.Model;
using YL.Web.Api.ThirdParty.Onboarding.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Test
{
    /// <summary>
    ///  Class for testing PaymentGatewayModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaymentGatewayModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaymentGatewayModel
        //private PaymentGatewayModel instance;

        public PaymentGatewayModelTests()
        {
            // TODO uncomment below to create an instance of PaymentGatewayModel
            //instance = new PaymentGatewayModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentGatewayModel
        /// </summary>
        [Fact]
        public void PaymentGatewayModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PaymentGatewayModel
            //Assert.IsInstanceOfType<PaymentGatewayModel> (instance, "variable 'instance' is a PaymentGatewayModel");
        }


        /// <summary>
        /// Test the property 'GatewayName'
        /// </summary>
        [Fact]
        public void GatewayNameTest()
        {
            // TODO unit test for the property 'GatewayName'
        }

    }

}
