/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Onboarding.Client.Api;
using YL.Web.Api.ThirdParty.Onboarding.Client.Model;
using YL.Web.Api.ThirdParty.Onboarding.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Test
{
    /// <summary>
    ///  Class for testing SaveBankStatementDocumentResultModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SaveBankStatementDocumentResultModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SaveBankStatementDocumentResultModel
        //private SaveBankStatementDocumentResultModel instance;

        public SaveBankStatementDocumentResultModelTests()
        {
            // TODO uncomment below to create an instance of SaveBankStatementDocumentResultModel
            //instance = new SaveBankStatementDocumentResultModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SaveBankStatementDocumentResultModel
        /// </summary>
        [Fact]
        public void SaveBankStatementDocumentResultModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SaveBankStatementDocumentResultModel
            //Assert.IsInstanceOfType<SaveBankStatementDocumentResultModel> (instance, "variable 'instance' is a SaveBankStatementDocumentResultModel");
        }


        /// <summary>
        /// Test the property 'LeadId'
        /// </summary>
        [Fact]
        public void LeadIdTest()
        {
            // TODO unit test for the property 'LeadId'
        }
        /// <summary>
        /// Test the property 'DocumentId'
        /// </summary>
        [Fact]
        public void DocumentIdTest()
        {
            // TODO unit test for the property 'DocumentId'
        }

    }

}
