/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Onboarding.Client.Api;
using YL.Web.Api.ThirdParty.Onboarding.Client.Model;
using YL.Web.Api.ThirdParty.Onboarding.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Test
{
    /// <summary>
    ///  Class for testing SignificantPersonDocumentsModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SignificantPersonDocumentsModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SignificantPersonDocumentsModel
        //private SignificantPersonDocumentsModel instance;

        public SignificantPersonDocumentsModelTests()
        {
            // TODO uncomment below to create an instance of SignificantPersonDocumentsModel
            //instance = new SignificantPersonDocumentsModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SignificantPersonDocumentsModel
        /// </summary>
        [Fact]
        public void SignificantPersonDocumentsModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SignificantPersonDocumentsModel
            //Assert.IsInstanceOfType<SignificantPersonDocumentsModel> (instance, "variable 'instance' is a SignificantPersonDocumentsModel");
        }


        /// <summary>
        /// Test the property 'PersonId'
        /// </summary>
        [Fact]
        public void PersonIdTest()
        {
            // TODO unit test for the property 'PersonId'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Documents'
        /// </summary>
        [Fact]
        public void DocumentsTest()
        {
            // TODO unit test for the property 'Documents'
        }

    }

}
