/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Onboarding.Client.Api;
using YL.Web.Api.ThirdParty.Onboarding.Client.Model;
using YL.Web.Api.ThirdParty.Onboarding.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Test
{
    /// <summary>
    ///  Class for testing SignificantPersonV2
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SignificantPersonV2Tests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SignificantPersonV2
        //private SignificantPersonV2 instance;

        public SignificantPersonV2Tests()
        {
            // TODO uncomment below to create an instance of SignificantPersonV2
            //instance = new SignificantPersonV2();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SignificantPersonV2
        /// </summary>
        [Fact]
        public void SignificantPersonV2InstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SignificantPersonV2
            //Assert.IsInstanceOfType<SignificantPersonV2> (instance, "variable 'instance' is a SignificantPersonV2");
        }


        /// <summary>
        /// Test the property 'PersonId'
        /// </summary>
        [Fact]
        public void PersonIdTest()
        {
            // TODO unit test for the property 'PersonId'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'Surname'
        /// </summary>
        [Fact]
        public void SurnameTest()
        {
            // TODO unit test for the property 'Surname'
        }
        /// <summary>
        /// Test the property 'TypeOfPerson'
        /// </summary>
        [Fact]
        public void TypeOfPersonTest()
        {
            // TODO unit test for the property 'TypeOfPerson'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'DateOfBirth'
        /// </summary>
        [Fact]
        public void DateOfBirthTest()
        {
            // TODO unit test for the property 'DateOfBirth'
        }
        /// <summary>
        /// Test the property 'PercentageOwned'
        /// </summary>
        [Fact]
        public void PercentageOwnedTest()
        {
            // TODO unit test for the property 'PercentageOwned'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'MobileNumber'
        /// </summary>
        [Fact]
        public void MobileNumberTest()
        {
            // TODO unit test for the property 'MobileNumber'
        }
        /// <summary>
        /// Test the property 'Nationality'
        /// </summary>
        [Fact]
        public void NationalityTest()
        {
            // TODO unit test for the property 'Nationality'
        }
        /// <summary>
        /// Test the property 'NiNumber'
        /// </summary>
        [Fact]
        public void NiNumberTest()
        {
            // TODO unit test for the property 'NiNumber'
        }

    }

}
