/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Onboarding.Client.Api;
using YL.Web.Api.ThirdParty.Onboarding.Client.Model;
using YL.Web.Api.ThirdParty.Onboarding.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Test
{
    /// <summary>
    ///  Class for testing SignificantPersonsModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SignificantPersonsModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SignificantPersonsModel
        //private SignificantPersonsModel instance;

        public SignificantPersonsModelTests()
        {
            // TODO uncomment below to create an instance of SignificantPersonsModel
            //instance = new SignificantPersonsModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SignificantPersonsModel
        /// </summary>
        [Fact]
        public void SignificantPersonsModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SignificantPersonsModel
            //Assert.IsInstanceOfType<SignificantPersonsModel> (instance, "variable 'instance' is a SignificantPersonsModel");
        }


        /// <summary>
        /// Test the property 'SignificantPersons'
        /// </summary>
        [Fact]
        public void SignificantPersonsTest()
        {
            // TODO unit test for the property 'SignificantPersons'
        }

    }

}
