/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Onboarding.Client.Api;
using YL.Web.Api.ThirdParty.Onboarding.Client.Model;
using YL.Web.Api.ThirdParty.Onboarding.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Test
{
    /// <summary>
    ///  Class for testing ThirdPartyOnboardingModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ThirdPartyOnboardingModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ThirdPartyOnboardingModel
        //private ThirdPartyOnboardingModel instance;

        public ThirdPartyOnboardingModelTests()
        {
            // TODO uncomment below to create an instance of ThirdPartyOnboardingModel
            //instance = new ThirdPartyOnboardingModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ThirdPartyOnboardingModel
        /// </summary>
        [Fact]
        public void ThirdPartyOnboardingModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ThirdPartyOnboardingModel
            //Assert.IsInstanceOfType<ThirdPartyOnboardingModel> (instance, "variable 'instance' is a ThirdPartyOnboardingModel");
        }


        /// <summary>
        /// Test the property 'ThirdPartyCustomerId'
        /// </summary>
        [Fact]
        public void ThirdPartyCustomerIdTest()
        {
            // TODO unit test for the property 'ThirdPartyCustomerId'
        }
        /// <summary>
        /// Test the property 'ThirdPartyLeadId'
        /// </summary>
        [Fact]
        public void ThirdPartyLeadIdTest()
        {
            // TODO unit test for the property 'ThirdPartyLeadId'
        }
        /// <summary>
        /// Test the property 'CountryISOCode'
        /// </summary>
        [Fact]
        public void CountryISOCodeTest()
        {
            // TODO unit test for the property 'CountryISOCode'
        }
        /// <summary>
        /// Test the property 'LoanCurrencyISOCode'
        /// </summary>
        [Fact]
        public void LoanCurrencyISOCodeTest()
        {
            // TODO unit test for the property 'LoanCurrencyISOCode'
        }
        /// <summary>
        /// Test the property 'MonthlyCardRevenue'
        /// </summary>
        [Fact]
        public void MonthlyCardRevenueTest()
        {
            // TODO unit test for the property 'MonthlyCardRevenue'
        }
        /// <summary>
        /// Test the property 'NumberOfPaymentsPerMonth'
        /// </summary>
        [Fact]
        public void NumberOfPaymentsPerMonthTest()
        {
            // TODO unit test for the property 'NumberOfPaymentsPerMonth'
        }
        /// <summary>
        /// Test the property 'SweepPercentage'
        /// </summary>
        [Fact]
        public void SweepPercentageTest()
        {
            // TODO unit test for the property 'SweepPercentage'
        }
        /// <summary>
        /// Test the property 'MonthsTrading'
        /// </summary>
        [Fact]
        public void MonthsTradingTest()
        {
            // TODO unit test for the property 'MonthsTrading'
        }
        /// <summary>
        /// Test the property 'LoanAmount'
        /// </summary>
        [Fact]
        public void LoanAmountTest()
        {
            // TODO unit test for the property 'LoanAmount'
        }
        /// <summary>
        /// Test the property 'KeyContactName'
        /// </summary>
        [Fact]
        public void KeyContactNameTest()
        {
            // TODO unit test for the property 'KeyContactName'
        }
        /// <summary>
        /// Test the property 'CompanyType'
        /// </summary>
        [Fact]
        public void CompanyTypeTest()
        {
            // TODO unit test for the property 'CompanyType'
        }
        /// <summary>
        /// Test the property 'CompanyName'
        /// </summary>
        [Fact]
        public void CompanyNameTest()
        {
            // TODO unit test for the property 'CompanyName'
        }
        /// <summary>
        /// Test the property 'CompanyWebsite'
        /// </summary>
        [Fact]
        public void CompanyWebsiteTest()
        {
            // TODO unit test for the property 'CompanyWebsite'
        }
        /// <summary>
        /// Test the property 'CompanyNumber'
        /// </summary>
        [Fact]
        public void CompanyNumberTest()
        {
            // TODO unit test for the property 'CompanyNumber'
        }
        /// <summary>
        /// Test the property 'VatNumber'
        /// </summary>
        [Fact]
        public void VatNumberTest()
        {
            // TODO unit test for the property 'VatNumber'
        }
        /// <summary>
        /// Test the property 'Mid'
        /// </summary>
        [Fact]
        public void MidTest()
        {
            // TODO unit test for the property 'Mid'
        }
        /// <summary>
        /// Test the property 'RegisteredAddress'
        /// </summary>
        [Fact]
        public void RegisteredAddressTest()
        {
            // TODO unit test for the property 'RegisteredAddress'
        }
        /// <summary>
        /// Test the property 'ContactPhoneNumber'
        /// </summary>
        [Fact]
        public void ContactPhoneNumberTest()
        {
            // TODO unit test for the property 'ContactPhoneNumber'
        }
        /// <summary>
        /// Test the property 'ContactEmailAddress'
        /// </summary>
        [Fact]
        public void ContactEmailAddressTest()
        {
            // TODO unit test for the property 'ContactEmailAddress'
        }
        /// <summary>
        /// Test the property 'NotificationURL'
        /// </summary>
        [Fact]
        public void NotificationURLTest()
        {
            // TODO unit test for the property 'NotificationURL'
        }
        /// <summary>
        /// Test the property 'AdditionalInfo'
        /// </summary>
        [Fact]
        public void AdditionalInfoTest()
        {
            // TODO unit test for the property 'AdditionalInfo'
        }

    }

}
