/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using YL.Web.Api.ThirdParty.Onboarding.Client.Api;
using YL.Web.Api.ThirdParty.Onboarding.Client.Model;
using YL.Web.Api.ThirdParty.Onboarding.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Test
{
    /// <summary>
    ///  Class for testing YesNoQuestionModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class YesNoQuestionModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for YesNoQuestionModel
        //private YesNoQuestionModel instance;

        public YesNoQuestionModelTests()
        {
            // TODO uncomment below to create an instance of YesNoQuestionModel
            //instance = new YesNoQuestionModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of YesNoQuestionModel
        /// </summary>
        [Fact]
        public void YesNoQuestionModelInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" YesNoQuestionModel
            //Assert.IsInstanceOfType<YesNoQuestionModel> (instance, "variable 'instance' is a YesNoQuestionModel");
        }


        /// <summary>
        /// Test the property 'Answer'
        /// </summary>
        [Fact]
        public void AnswerTest()
        {
            // TODO unit test for the property 'Answer'
        }
        /// <summary>
        /// Test the property 'AdditionalInformation'
        /// </summary>
        [Fact]
        public void AdditionalInformationTest()
        {
            // TODO unit test for the property 'AdditionalInformation'
        }

    }

}
