/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = YL.Web.Api.ThirdParty.Onboarding.Client.Client.OpenAPIDateConverter;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Model
{
    /// <summary>
    /// The view model for a document signing
    /// </summary>
    [DataContract]
    public partial class DocumentSigningViewModel :  IEquatable<DocumentSigningViewModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentSigningViewModel" /> class.
        /// </summary>
        /// <param name="documentSigningId">Gets or sets the document signing id (a GUID).</param>
        /// <param name="documents">Gets or sets a list of DocumentMetadataModels representing the unsigned documents.</param>
        /// <param name="signatorySigningViews">Gets or sets a list of SignatorySigningViewModels.</param>
        /// <param name="signedDocuments">Gets or sets a list of DocumentMetadataModels representing the signed documents.</param>
        public DocumentSigningViewModel(Guid documentSigningId = default(Guid), List<DocumentMetadataModel> documents = default(List<DocumentMetadataModel>), List<SignatorySigningViewModel> signatorySigningViews = default(List<SignatorySigningViewModel>), List<DocumentMetadataModel> signedDocuments = default(List<DocumentMetadataModel>))
        {
            this.DocumentSigningId = documentSigningId;
            this.Documents = documents;
            this.SignatorySigningViews = signatorySigningViews;
            this.SignedDocuments = signedDocuments;
        }
        
        /// <summary>
        /// Gets or sets the document signing id (a GUID)
        /// </summary>
        /// <value>Gets or sets the document signing id (a GUID)</value>
        [DataMember(Name="documentSigningId", EmitDefaultValue=false)]
        public Guid DocumentSigningId { get; set; }

        /// <summary>
        /// Gets or sets a list of DocumentMetadataModels representing the unsigned documents
        /// </summary>
        /// <value>Gets or sets a list of DocumentMetadataModels representing the unsigned documents</value>
        [DataMember(Name="documents", EmitDefaultValue=false)]
        public List<DocumentMetadataModel> Documents { get; set; }

        /// <summary>
        /// Gets or sets a list of SignatorySigningViewModels
        /// </summary>
        /// <value>Gets or sets a list of SignatorySigningViewModels</value>
        [DataMember(Name="signatorySigningViews", EmitDefaultValue=false)]
        public List<SignatorySigningViewModel> SignatorySigningViews { get; set; }

        /// <summary>
        /// Gets or sets a list of DocumentMetadataModels representing the signed documents
        /// </summary>
        /// <value>Gets or sets a list of DocumentMetadataModels representing the signed documents</value>
        [DataMember(Name="signedDocuments", EmitDefaultValue=false)]
        public List<DocumentMetadataModel> SignedDocuments { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DocumentSigningViewModel {\n");
            sb.Append("  DocumentSigningId: ").Append(DocumentSigningId).Append("\n");
            sb.Append("  Documents: ").Append(Documents).Append("\n");
            sb.Append("  SignatorySigningViews: ").Append(SignatorySigningViews).Append("\n");
            sb.Append("  SignedDocuments: ").Append(SignedDocuments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DocumentSigningViewModel);
        }

        /// <summary>
        /// Returns true if DocumentSigningViewModel instances are equal
        /// </summary>
        /// <param name="input">Instance of DocumentSigningViewModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DocumentSigningViewModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DocumentSigningId == input.DocumentSigningId ||
                    (this.DocumentSigningId != null &&
                    this.DocumentSigningId.Equals(input.DocumentSigningId))
                ) && 
                (
                    this.Documents == input.Documents ||
                    this.Documents != null &&
                    input.Documents != null &&
                    this.Documents.SequenceEqual(input.Documents)
                ) && 
                (
                    this.SignatorySigningViews == input.SignatorySigningViews ||
                    this.SignatorySigningViews != null &&
                    input.SignatorySigningViews != null &&
                    this.SignatorySigningViews.SequenceEqual(input.SignatorySigningViews)
                ) && 
                (
                    this.SignedDocuments == input.SignedDocuments ||
                    this.SignedDocuments != null &&
                    input.SignedDocuments != null &&
                    this.SignedDocuments.SequenceEqual(input.SignedDocuments)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DocumentSigningId != null)
                    hashCode = hashCode * 59 + this.DocumentSigningId.GetHashCode();
                if (this.Documents != null)
                    hashCode = hashCode * 59 + this.Documents.GetHashCode();
                if (this.SignatorySigningViews != null)
                    hashCode = hashCode * 59 + this.SignatorySigningViews.GetHashCode();
                if (this.SignedDocuments != null)
                    hashCode = hashCode * 59 + this.SignedDocuments.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
