/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = YL.Web.Api.ThirdParty.Onboarding.Client.Client.OpenAPIDateConverter;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Model
{
    /// <summary>
    /// Free Text Question Model
    /// </summary>
    [DataContract]
    public partial class FreeTextQuestionModel :  IEquatable<FreeTextQuestionModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FreeTextQuestionModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FreeTextQuestionModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FreeTextQuestionModel" /> class.
        /// </summary>
        /// <param name="answer">Gets or sets the answer to the free text question (required).</param>
        public FreeTextQuestionModel(string answer = default(string))
        {
            // to ensure "answer" is required (not null)
            if (answer == null)
            {
                throw new InvalidDataException("answer is a required property for FreeTextQuestionModel and cannot be null");
            }
            else
            {
                this.Answer = answer;
            }

        }
        
        /// <summary>
        /// Gets or sets the answer to the free text question
        /// </summary>
        /// <value>Gets or sets the answer to the free text question</value>
        [DataMember(Name="answer", EmitDefaultValue=false)]
        public string Answer { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FreeTextQuestionModel {\n");
            sb.Append("  Answer: ").Append(Answer).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FreeTextQuestionModel);
        }

        /// <summary>
        /// Returns true if FreeTextQuestionModel instances are equal
        /// </summary>
        /// <param name="input">Instance of FreeTextQuestionModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FreeTextQuestionModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Answer == input.Answer ||
                    (this.Answer != null &&
                    this.Answer.Equals(input.Answer))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Answer != null)
                    hashCode = hashCode * 59 + this.Answer.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Answer (string) minLength
            if(this.Answer != null && this.Answer.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Answer, length must be greater than 1.", new [] { "Answer" });
            }

            yield break;
        }
    }

}
