/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = YL.Web.Api.ThirdParty.Onboarding.Client.Client.OpenAPIDateConverter;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Model
{
    /// <summary>
    /// Model containing details about an offer
    /// </summary>
    [DataContract]
    public partial class OfferStepModel :  IEquatable<OfferStepModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OfferStepModel" /> class.
        /// </summary>
        /// <param name="leadId">Gets or sets the lead id.</param>
        /// <param name="youWillGet">Gets or sets the amount that the lead will receive if offer is accepted.</param>
        /// <param name="youWillRepay">Gets or sets the amount that the lead will repay.</param>
        /// <param name="currencyISOCode">Gets or sets the currency ISO code for the offer.</param>
        /// <param name="sweep">Gets or sets the sweep, which is the percentage of the settlement which is allocated to repaying the loan.</param>
        /// <param name="unsignedLoanDocument">unsignedLoanDocument.</param>
        /// <param name="unsignedLoanDocumentDownloaded">Gets or sets a value indicating whether the unsigned loan document has been downloaded.</param>
        /// <param name="unsignedAccountDocument">unsignedAccountDocument.</param>
        /// <param name="unsignedAccountDocumentDownloaded">Gets or sets a value indicating whether the unsigned loan document has been downloaded.</param>
        /// <param name="documentSigningId">Gets or sets the document signing id.</param>
        /// <param name="sortCode">Gets or sets the sort code of the lead&#39;s account.</param>
        /// <param name="accountNumber">Gets or sets the account number for the lead.</param>
        /// <param name="swift">Gets or sets the swift code for the lead&#39;s account.</param>
        /// <param name="iban">Gets or sets the IBAN for the lead&#39;s account.</param>
        /// <param name="bankName">Gets or sets the name of the bank associated with the lead&#39;s account.</param>
        /// <param name="confirmedCompanyAccount">Gets or sets a value indicating whether the account is confirmed to be the company account.</param>
        public OfferStepModel(Guid leadId = default(Guid), double youWillGet = default(double), double youWillRepay = default(double), string currencyISOCode = default(string), double sweep = default(double), DocumentMetadataModel unsignedLoanDocument = default(DocumentMetadataModel), bool unsignedLoanDocumentDownloaded = default(bool), DocumentMetadataModel unsignedAccountDocument = default(DocumentMetadataModel), bool unsignedAccountDocumentDownloaded = default(bool), Guid documentSigningId = default(Guid), string sortCode = default(string), string accountNumber = default(string), string swift = default(string), string iban = default(string), string bankName = default(string), bool confirmedCompanyAccount = default(bool))
        {
            this.LeadId = leadId;
            this.YouWillGet = youWillGet;
            this.YouWillRepay = youWillRepay;
            this.CurrencyISOCode = currencyISOCode;
            this.Sweep = sweep;
            this.UnsignedLoanDocument = unsignedLoanDocument;
            this.UnsignedLoanDocumentDownloaded = unsignedLoanDocumentDownloaded;
            this.UnsignedAccountDocument = unsignedAccountDocument;
            this.UnsignedAccountDocumentDownloaded = unsignedAccountDocumentDownloaded;
            this.DocumentSigningId = documentSigningId;
            this.SortCode = sortCode;
            this.AccountNumber = accountNumber;
            this.Swift = swift;
            this.Iban = iban;
            this.BankName = bankName;
            this.ConfirmedCompanyAccount = confirmedCompanyAccount;
        }
        
        /// <summary>
        /// Gets or sets the lead id
        /// </summary>
        /// <value>Gets or sets the lead id</value>
        [DataMember(Name="leadId", EmitDefaultValue=false)]
        public Guid LeadId { get; set; }

        /// <summary>
        /// Gets or sets the amount that the lead will receive if offer is accepted
        /// </summary>
        /// <value>Gets or sets the amount that the lead will receive if offer is accepted</value>
        [DataMember(Name="youWillGet", EmitDefaultValue=false)]
        public double YouWillGet { get; set; }

        /// <summary>
        /// Gets or sets the amount that the lead will repay
        /// </summary>
        /// <value>Gets or sets the amount that the lead will repay</value>
        [DataMember(Name="youWillRepay", EmitDefaultValue=false)]
        public double YouWillRepay { get; set; }

        /// <summary>
        /// Gets or sets the currency ISO code for the offer
        /// </summary>
        /// <value>Gets or sets the currency ISO code for the offer</value>
        [DataMember(Name="currencyISOCode", EmitDefaultValue=false)]
        public string CurrencyISOCode { get; set; }

        /// <summary>
        /// Gets or sets the sweep, which is the percentage of the settlement which is allocated to repaying the loan
        /// </summary>
        /// <value>Gets or sets the sweep, which is the percentage of the settlement which is allocated to repaying the loan</value>
        [DataMember(Name="sweep", EmitDefaultValue=false)]
        public double Sweep { get; set; }

        /// <summary>
        /// Gets or Sets UnsignedLoanDocument
        /// </summary>
        [DataMember(Name="unsignedLoanDocument", EmitDefaultValue=false)]
        public DocumentMetadataModel UnsignedLoanDocument { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the unsigned loan document has been downloaded
        /// </summary>
        /// <value>Gets or sets a value indicating whether the unsigned loan document has been downloaded</value>
        [DataMember(Name="unsignedLoanDocumentDownloaded", EmitDefaultValue=false)]
        public bool UnsignedLoanDocumentDownloaded { get; set; }

        /// <summary>
        /// Gets or Sets UnsignedAccountDocument
        /// </summary>
        [DataMember(Name="unsignedAccountDocument", EmitDefaultValue=false)]
        public DocumentMetadataModel UnsignedAccountDocument { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the unsigned loan document has been downloaded
        /// </summary>
        /// <value>Gets or sets a value indicating whether the unsigned loan document has been downloaded</value>
        [DataMember(Name="unsignedAccountDocumentDownloaded", EmitDefaultValue=false)]
        public bool UnsignedAccountDocumentDownloaded { get; set; }

        /// <summary>
        /// Gets or sets the document signing id
        /// </summary>
        /// <value>Gets or sets the document signing id</value>
        [DataMember(Name="documentSigningId", EmitDefaultValue=false)]
        public Guid DocumentSigningId { get; set; }

        /// <summary>
        /// Gets or sets the sort code of the lead&#39;s account
        /// </summary>
        /// <value>Gets or sets the sort code of the lead&#39;s account</value>
        [DataMember(Name="sortCode", EmitDefaultValue=false)]
        public string SortCode { get; set; }

        /// <summary>
        /// Gets or sets the account number for the lead
        /// </summary>
        /// <value>Gets or sets the account number for the lead</value>
        [DataMember(Name="accountNumber", EmitDefaultValue=false)]
        public string AccountNumber { get; set; }

        /// <summary>
        /// Gets or sets the swift code for the lead&#39;s account
        /// </summary>
        /// <value>Gets or sets the swift code for the lead&#39;s account</value>
        [DataMember(Name="swift", EmitDefaultValue=false)]
        public string Swift { get; set; }

        /// <summary>
        /// Gets or sets the IBAN for the lead&#39;s account
        /// </summary>
        /// <value>Gets or sets the IBAN for the lead&#39;s account</value>
        [DataMember(Name="iban", EmitDefaultValue=false)]
        public string Iban { get; set; }

        /// <summary>
        /// Gets or sets the name of the bank associated with the lead&#39;s account
        /// </summary>
        /// <value>Gets or sets the name of the bank associated with the lead&#39;s account</value>
        [DataMember(Name="bankName", EmitDefaultValue=false)]
        public string BankName { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether the account is confirmed to be the company account
        /// </summary>
        /// <value>Gets or sets a value indicating whether the account is confirmed to be the company account</value>
        [DataMember(Name="confirmedCompanyAccount", EmitDefaultValue=false)]
        public bool ConfirmedCompanyAccount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OfferStepModel {\n");
            sb.Append("  LeadId: ").Append(LeadId).Append("\n");
            sb.Append("  YouWillGet: ").Append(YouWillGet).Append("\n");
            sb.Append("  YouWillRepay: ").Append(YouWillRepay).Append("\n");
            sb.Append("  CurrencyISOCode: ").Append(CurrencyISOCode).Append("\n");
            sb.Append("  Sweep: ").Append(Sweep).Append("\n");
            sb.Append("  UnsignedLoanDocument: ").Append(UnsignedLoanDocument).Append("\n");
            sb.Append("  UnsignedLoanDocumentDownloaded: ").Append(UnsignedLoanDocumentDownloaded).Append("\n");
            sb.Append("  UnsignedAccountDocument: ").Append(UnsignedAccountDocument).Append("\n");
            sb.Append("  UnsignedAccountDocumentDownloaded: ").Append(UnsignedAccountDocumentDownloaded).Append("\n");
            sb.Append("  DocumentSigningId: ").Append(DocumentSigningId).Append("\n");
            sb.Append("  SortCode: ").Append(SortCode).Append("\n");
            sb.Append("  AccountNumber: ").Append(AccountNumber).Append("\n");
            sb.Append("  Swift: ").Append(Swift).Append("\n");
            sb.Append("  Iban: ").Append(Iban).Append("\n");
            sb.Append("  BankName: ").Append(BankName).Append("\n");
            sb.Append("  ConfirmedCompanyAccount: ").Append(ConfirmedCompanyAccount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OfferStepModel);
        }

        /// <summary>
        /// Returns true if OfferStepModel instances are equal
        /// </summary>
        /// <param name="input">Instance of OfferStepModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OfferStepModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LeadId == input.LeadId ||
                    (this.LeadId != null &&
                    this.LeadId.Equals(input.LeadId))
                ) && 
                (
                    this.YouWillGet == input.YouWillGet ||
                    this.YouWillGet.Equals(input.YouWillGet)
                ) && 
                (
                    this.YouWillRepay == input.YouWillRepay ||
                    this.YouWillRepay.Equals(input.YouWillRepay)
                ) && 
                (
                    this.CurrencyISOCode == input.CurrencyISOCode ||
                    (this.CurrencyISOCode != null &&
                    this.CurrencyISOCode.Equals(input.CurrencyISOCode))
                ) && 
                (
                    this.Sweep == input.Sweep ||
                    this.Sweep.Equals(input.Sweep)
                ) && 
                (
                    this.UnsignedLoanDocument == input.UnsignedLoanDocument ||
                    (this.UnsignedLoanDocument != null &&
                    this.UnsignedLoanDocument.Equals(input.UnsignedLoanDocument))
                ) && 
                (
                    this.UnsignedLoanDocumentDownloaded == input.UnsignedLoanDocumentDownloaded ||
                    this.UnsignedLoanDocumentDownloaded.Equals(input.UnsignedLoanDocumentDownloaded)
                ) && 
                (
                    this.UnsignedAccountDocument == input.UnsignedAccountDocument ||
                    (this.UnsignedAccountDocument != null &&
                    this.UnsignedAccountDocument.Equals(input.UnsignedAccountDocument))
                ) && 
                (
                    this.UnsignedAccountDocumentDownloaded == input.UnsignedAccountDocumentDownloaded ||
                    this.UnsignedAccountDocumentDownloaded.Equals(input.UnsignedAccountDocumentDownloaded)
                ) && 
                (
                    this.DocumentSigningId == input.DocumentSigningId ||
                    (this.DocumentSigningId != null &&
                    this.DocumentSigningId.Equals(input.DocumentSigningId))
                ) && 
                (
                    this.SortCode == input.SortCode ||
                    (this.SortCode != null &&
                    this.SortCode.Equals(input.SortCode))
                ) && 
                (
                    this.AccountNumber == input.AccountNumber ||
                    (this.AccountNumber != null &&
                    this.AccountNumber.Equals(input.AccountNumber))
                ) && 
                (
                    this.Swift == input.Swift ||
                    (this.Swift != null &&
                    this.Swift.Equals(input.Swift))
                ) && 
                (
                    this.Iban == input.Iban ||
                    (this.Iban != null &&
                    this.Iban.Equals(input.Iban))
                ) && 
                (
                    this.BankName == input.BankName ||
                    (this.BankName != null &&
                    this.BankName.Equals(input.BankName))
                ) && 
                (
                    this.ConfirmedCompanyAccount == input.ConfirmedCompanyAccount ||
                    this.ConfirmedCompanyAccount.Equals(input.ConfirmedCompanyAccount)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LeadId != null)
                    hashCode = hashCode * 59 + this.LeadId.GetHashCode();
                hashCode = hashCode * 59 + this.YouWillGet.GetHashCode();
                hashCode = hashCode * 59 + this.YouWillRepay.GetHashCode();
                if (this.CurrencyISOCode != null)
                    hashCode = hashCode * 59 + this.CurrencyISOCode.GetHashCode();
                hashCode = hashCode * 59 + this.Sweep.GetHashCode();
                if (this.UnsignedLoanDocument != null)
                    hashCode = hashCode * 59 + this.UnsignedLoanDocument.GetHashCode();
                hashCode = hashCode * 59 + this.UnsignedLoanDocumentDownloaded.GetHashCode();
                if (this.UnsignedAccountDocument != null)
                    hashCode = hashCode * 59 + this.UnsignedAccountDocument.GetHashCode();
                hashCode = hashCode * 59 + this.UnsignedAccountDocumentDownloaded.GetHashCode();
                if (this.DocumentSigningId != null)
                    hashCode = hashCode * 59 + this.DocumentSigningId.GetHashCode();
                if (this.SortCode != null)
                    hashCode = hashCode * 59 + this.SortCode.GetHashCode();
                if (this.AccountNumber != null)
                    hashCode = hashCode * 59 + this.AccountNumber.GetHashCode();
                if (this.Swift != null)
                    hashCode = hashCode * 59 + this.Swift.GetHashCode();
                if (this.Iban != null)
                    hashCode = hashCode * 59 + this.Iban.GetHashCode();
                if (this.BankName != null)
                    hashCode = hashCode * 59 + this.BankName.GetHashCode();
                hashCode = hashCode * 59 + this.ConfirmedCompanyAccount.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
