/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = YL.Web.Api.ThirdParty.Onboarding.Client.Client.OpenAPIDateConverter;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Model
{
    /// <summary>
    /// Payment Gateway Model
    /// </summary>
    [DataContract]
    public partial class PaymentGatewayModel :  IEquatable<PaymentGatewayModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentGatewayModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PaymentGatewayModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentGatewayModel" /> class.
        /// </summary>
        /// <param name="gatewayName">Gets or sets the payment gateway name (required).</param>
        public PaymentGatewayModel(string gatewayName = default(string))
        {
            // to ensure "gatewayName" is required (not null)
            if (gatewayName == null)
            {
                throw new InvalidDataException("gatewayName is a required property for PaymentGatewayModel and cannot be null");
            }
            else
            {
                this.GatewayName = gatewayName;
            }

        }
        
        /// <summary>
        /// Gets or sets the payment gateway name
        /// </summary>
        /// <value>Gets or sets the payment gateway name</value>
        [DataMember(Name="gatewayName", EmitDefaultValue=false)]
        public string GatewayName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaymentGatewayModel {\n");
            sb.Append("  GatewayName: ").Append(GatewayName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PaymentGatewayModel);
        }

        /// <summary>
        /// Returns true if PaymentGatewayModel instances are equal
        /// </summary>
        /// <param name="input">Instance of PaymentGatewayModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaymentGatewayModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.GatewayName == input.GatewayName ||
                    (this.GatewayName != null &&
                    this.GatewayName.Equals(input.GatewayName))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.GatewayName != null)
                    hashCode = hashCode * 59 + this.GatewayName.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // GatewayName (string) maxLength
            if(this.GatewayName != null && this.GatewayName.Length > 255)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for GatewayName, length must be less than 255.", new [] { "GatewayName" });
            }

            // GatewayName (string) minLength
            if(this.GatewayName != null && this.GatewayName.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for GatewayName, length must be greater than 1.", new [] { "GatewayName" });
            }

            yield break;
        }
    }

}
