/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = YL.Web.Api.ThirdParty.Onboarding.Client.Client.OpenAPIDateConverter;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Model
{
    /// <summary>
    /// The result of adding a document to a significant person
    /// </summary>
    [DataContract]
    public partial class SaveSignficantPersonKycDocumentResultModel :  IEquatable<SaveSignficantPersonKycDocumentResultModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SaveSignficantPersonKycDocumentResultModel" /> class.
        /// </summary>
        /// <param name="leadId">Gets or sets the Lead Id.</param>
        /// <param name="significantPersonId">Gets or sets the Significant Person Id.</param>
        /// <param name="documentId">Gets or sets the Document Id.</param>
        public SaveSignficantPersonKycDocumentResultModel(Guid leadId = default(Guid), Guid significantPersonId = default(Guid), Guid documentId = default(Guid))
        {
            this.LeadId = leadId;
            this.SignificantPersonId = significantPersonId;
            this.DocumentId = documentId;
        }
        
        /// <summary>
        /// Gets or sets the Lead Id
        /// </summary>
        /// <value>Gets or sets the Lead Id</value>
        [DataMember(Name="leadId", EmitDefaultValue=false)]
        public Guid LeadId { get; set; }

        /// <summary>
        /// Gets or sets the Significant Person Id
        /// </summary>
        /// <value>Gets or sets the Significant Person Id</value>
        [DataMember(Name="significantPersonId", EmitDefaultValue=false)]
        public Guid SignificantPersonId { get; set; }

        /// <summary>
        /// Gets or sets the Document Id
        /// </summary>
        /// <value>Gets or sets the Document Id</value>
        [DataMember(Name="documentId", EmitDefaultValue=false)]
        public Guid DocumentId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SaveSignficantPersonKycDocumentResultModel {\n");
            sb.Append("  LeadId: ").Append(LeadId).Append("\n");
            sb.Append("  SignificantPersonId: ").Append(SignificantPersonId).Append("\n");
            sb.Append("  DocumentId: ").Append(DocumentId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SaveSignficantPersonKycDocumentResultModel);
        }

        /// <summary>
        /// Returns true if SaveSignficantPersonKycDocumentResultModel instances are equal
        /// </summary>
        /// <param name="input">Instance of SaveSignficantPersonKycDocumentResultModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SaveSignficantPersonKycDocumentResultModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.LeadId == input.LeadId ||
                    (this.LeadId != null &&
                    this.LeadId.Equals(input.LeadId))
                ) && 
                (
                    this.SignificantPersonId == input.SignificantPersonId ||
                    (this.SignificantPersonId != null &&
                    this.SignificantPersonId.Equals(input.SignificantPersonId))
                ) && 
                (
                    this.DocumentId == input.DocumentId ||
                    (this.DocumentId != null &&
                    this.DocumentId.Equals(input.DocumentId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.LeadId != null)
                    hashCode = hashCode * 59 + this.LeadId.GetHashCode();
                if (this.SignificantPersonId != null)
                    hashCode = hashCode * 59 + this.SignificantPersonId.GetHashCode();
                if (this.DocumentId != null)
                    hashCode = hashCode * 59 + this.DocumentId.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
