/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using YL.Web.Api.ThirdParty.Onboarding.Client.Client;
using YL.Web.Api.ThirdParty.Onboarding.Client.Api;
using YL.Web.Api.ThirdParty.Onboarding.Client.Model;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Test
{
    /// <summary>
    ///  Class for testing DocumentSigningApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DocumentSigningApiTests : IDisposable
    {
        private DocumentSigningApi instance;

        public DocumentSigningApiTests()
        {
            instance = new DocumentSigningApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocumentSigningApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' DocumentSigningApi
            //Assert.IsType(typeof(DocumentSigningApi), instance, "instance is a DocumentSigningApi");
        }

        
        /// <summary>
        /// Test DocumentSigningDocumentSigningIdGet
        /// </summary>
        [Fact]
        public void DocumentSigningDocumentSigningIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid documentSigningId = null;
            //string apiVersion = null;
            //var response = instance.DocumentSigningDocumentSigningIdGet(documentSigningId, apiVersion);
            //Assert.IsType<DocumentSigningViewModel> (response, "response is DocumentSigningViewModel");
        }
        
    }

}
