/* 
 * YouLend Third Party Onboarding API
 *
 * Through this API you can can initiate the process of onboarding a borrower with YouLend
 *
 * The version of the OpenAPI document: 1.0
 * Contact: mark.ufland@youlend.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using YL.Web.Api.ThirdParty.Onboarding.Client.Client;
using YL.Web.Api.ThirdParty.Onboarding.Client.Api;
using YL.Web.Api.ThirdParty.Onboarding.Client.Model;

namespace YL.Web.Api.ThirdParty.Onboarding.Client.Test
{
    /// <summary>
    ///  Class for testing LeadsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class LeadsApiTests : IDisposable
    {
        private LeadsApi instance;

        public LeadsApiTests()
        {
            instance = new LeadsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LeadsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' LeadsApi
            //Assert.IsType(typeof(LeadsApi), instance, "instance is a LeadsApi");
        }

        
        /// <summary>
        /// Test LeadsLeadIdAccountdetailsPut
        /// </summary>
        [Fact]
        public void LeadsLeadIdAccountdetailsPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid leadId = null;
            //string apiVersion = null;
            //AccountDetailsModel accountDetailsModel = null;
            //instance.LeadsLeadIdAccountdetailsPut(leadId, apiVersion, accountDetailsModel);
            
        }
        
        /// <summary>
        /// Test LeadsLeadIdDocumentsBankstatementsPost
        /// </summary>
        [Fact]
        public void LeadsLeadIdDocumentsBankstatementsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid leadId = null;
            //string apiVersion = null;
            //System.IO.Stream file = null;
            //var response = instance.LeadsLeadIdDocumentsBankstatementsPost(leadId, apiVersion, file);
            //Assert.IsType<SaveBankStatementDocumentResultModel> (response, "response is SaveBankStatementDocumentResultModel");
        }
        
        /// <summary>
        /// Test LeadsLeadIdDocumentsPaymentdataPost
        /// </summary>
        [Fact]
        public void LeadsLeadIdDocumentsPaymentdataPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid leadId = null;
            //string apiVersion = null;
            //System.IO.Stream file = null;
            //var response = instance.LeadsLeadIdDocumentsPaymentdataPost(leadId, apiVersion, file);
            //Assert.IsType<SavePaymentDataDocumentResultModel> (response, "response is SavePaymentDataDocumentResultModel");
        }
        
        /// <summary>
        /// Test LeadsLeadIdDocumentsSignificantpersonsSignificantPersonIdKycDocumentTypePost
        /// </summary>
        [Fact]
        public void LeadsLeadIdDocumentsSignificantpersonsSignificantPersonIdKycDocumentTypePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid leadId = null;
            //Guid significantPersonId = null;
            //string kycDocumentType = null;
            //string apiVersion = null;
            //System.IO.Stream file = null;
            //var response = instance.LeadsLeadIdDocumentsSignificantpersonsSignificantPersonIdKycDocumentTypePost(leadId, significantPersonId, kycDocumentType, apiVersion, file);
            //Assert.IsType<SaveSignficantPersonKycDocumentResultModel> (response, "response is SaveSignficantPersonKycDocumentResultModel");
        }
        
        /// <summary>
        /// Test LeadsLeadIdKycquestionsPut
        /// </summary>
        [Fact]
        public void LeadsLeadIdKycquestionsPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid leadId = null;
            //string apiVersion = null;
            //KycQuestionsModel kycQuestionsModel = null;
            //instance.LeadsLeadIdKycquestionsPut(leadId, apiVersion, kycQuestionsModel);
            
        }
        
        /// <summary>
        /// Test LeadsLeadIdPaymentgatewaysPost
        /// </summary>
        [Fact]
        public void LeadsLeadIdPaymentgatewaysPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid leadId = null;
            //string apiVersion = null;
            //PaymentGatewayModel paymentGatewayModel = null;
            //instance.LeadsLeadIdPaymentgatewaysPost(leadId, apiVersion, paymentGatewayModel);
            
        }
        
        /// <summary>
        /// Test LeadsLeadIdSignificantpersonsPut
        /// </summary>
        [Fact]
        public void LeadsLeadIdSignificantpersonsPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid leadId = null;
            //string apiVersion = null;
            //SignificantPersonsModel significantPersonsModel = null;
            //var response = instance.LeadsLeadIdSignificantpersonsPut(leadId, apiVersion, significantPersonsModel);
            //Assert.IsType<SaveSignificantPersonsResultModel> (response, "response is SaveSignificantPersonsResultModel");
        }
        
        /// <summary>
        /// Test LeadsPost
        /// </summary>
        [Fact]
        public void LeadsPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string apiVersion = null;
            //ThirdPartyOnboardingModel thirdPartyOnboardingModel = null;
            //var response = instance.LeadsPost(apiVersion, thirdPartyOnboardingModel);
            //Assert.IsType<CreateThirdPartyAdvanceOnboardingResultModel> (response, "response is CreateThirdPartyAdvanceOnboardingResultModel");
        }
        
    }

}
